### ISSUE TITLE
[ERROR] playermodels

### ISSUE THREAD

**Issue by Ayrton09** [shanapu/MyStore#10] opened 2019-12-08 02:24 UTC
hello, thomas!

im using sourcemod 1.10 GAME: CSGO

everything is working fine but when i set a player model disappears at round start or mapchange

and when i choose some skin i got a error like not precached and the server and client crash

im using sm_downloader from swat and not having problems with the zepyrous store

2/07/2019 - 23:20:24: [SM]   [0] CreateTimer
L 12/07/2019 - 23:20:24: [SM]   [1] Line 224, addons/sourcemod/scripting/mystore_item_playermodel.sp::Event_PlayerSpawn
L 12/07/2019 - 23:20:24: [SM] Exception reported: Could not create timer, no more handles
L 12/07/2019 - 23:20:24: [SM] Blaming: mystore_item_playermodel.smx
L 12/07/2019 - 23:20:24: [SM] Call stack trace:
L 12/07/2019 - 23:20:24: [SM]   [0] CreateTimer
L 12/07/2019 - 23:20:24: [SM]   [1] Line 224, addons/sourcemod/scripting/mystore_item_playermodel.sp::Event_PlayerSpawn
L 12/07/2019 - 23:20:30: Error log file session closed.
L 12/07/2019 - 23:20:56: SourceMod error session started
L 12/07/2019 - 23:20:56: Info (map "35hp_2_2015") (file "csgo\addons\sourcemod\logs\errors_20191207.log")
L 12/07/2019 - 23:20:56: [SM] Exception reported: Could not create timer, no more handles
L 12/07/2019 - 23:20:56: [SM] Blaming: mystore_item_playermodel.smx
L 12/07/2019 - 23:20:56: [SM] Call stack trace:
L 12/07/2019 - 23:20:56: [SM]   [0] CreateTimer
L 12/07/2019 - 23:20:56: [SM]   [1] Line 224, addons/sourcemod/scripting/mystore_item_playermodel.sp::Event_PlayerSpawn
L 12/07/2019 - 23:20:57: [SM] Exception reported: Could not create timer, no more handles
L 12/07/2019 - 23:20:57: [SM] Blaming: mystore_item_playermodel.smx
L 12/07/2019 - 23:20:57: [SM] Call stack trace:
L 12/07/2019 - 23:20:57: [SM]   [0] CreateTimer
L 12/07/2019 - 23:20:57: [SM]   [1] Line 224, addons/sourcemod/scripting/mystore_item_playermodel.sp::Event_PlayerSpawn
L 12/07/2019 - 23:21:09: [SM] Exception reported: Could not create timer, no more handles
L 12/07/2019 - 23:21:09: [SM] Blaming: mystore_item_playermodel.smx
L 12/07/2019 - 23:21:09: [SM] Call stack trace:
L 12/07/2019 - 23:21:09: [SM]   [0] CreateTimer
L 12/07/2019 - 23:21:09: [SM]   [1] Line 253, addons/sourcemod/scripting/mystore_item_playermodel.sp::SetClientModel
L 12/07/2019 - 23:21:09: [SM]   [2] Line 181, addons/sourcemod/scripting/mystore_item_playermodel.sp::PlayerModels_Equip
L 12/07/2019 - 23:21:09: [SM]   [4] Call_Finish
L 12/07/2019 - 23:21:09: [SM]   [5] Line 3509, addons/sourcemod/scripting/mystore_core.sp::UseItem
L 12/07/2019 - 23:21:09: [SM]   [6] Line 1728, addons/sourcemod/scripting/mystore_core.sp::MenuHandler_Preview
L 12/07/2019 - 23:21:22: [SM] Exception reported: Could not create timer, no more handles
L 12/07/2019 - 23:21:22: [SM] Blaming: mystore_item_playermodel.smx
L 12/07/2019 - 23:21:22: [SM] Call stack trace:
L 12/07/2019 - 23:21:22: [SM]   [0] CreateTimer
L 12/07/2019 - 23:21:22: [SM]   [1] Line 224, addons/sourcemod/scripting/mystore_item_playermodel.sp::Event_PlayerSpawn
L 12/07/2019 - 23:21:23: [SM] Exception reported: Could not create timer, no more handles
L 12/07/2019 - 23:21:23: [SM] Blaming: mystore_item_playermodel.smx
L 12/07/2019 - 23:21:23: [SM] Call stack trace:
L 12/07/2019 - 23:21:23: [SM]   [0] CreateTimer
L 12/07/2019 - 23:21:23: [SM]   [1] Line 224, addons/sourcemod/scripting/mystore_item_playermodel.sp::Event_PlayerSpawn

edit: this is a new log error crashing my server

L 12/08/2019 - 16:07:11: Error log file session closed.
L 12/08/2019 - 16:07:12: SourceMod error session started
L 12/08/2019 - 16:07:12: Info (map "35hp_2_2015") (file "csgo\addons\sourcemod\logs\errors_20191208.log")
L 12/08/2019 - 16:07:12: [SM] Exception reported: invalid handle 0 (error: 4)
L 12/08/2019 - 16:07:12: [SM] Blaming: mystore_item_playermodel.smx
L 12/08/2019 - 16:07:12: [SM] Call stack trace:
L 12/08/2019 - 16:07:12: [SM]   [0] ReadFileLine
L 12/08/2019 - 16:07:12: [SM]   [1] Line 108, /home/travis/build/shanapu/MyStore/addons/sourcemod/scripting/include/smartdm.inc::Downloader_GetMaterialsFromVMT
L 12/08/2019 - 16:07:12: [SM]   [2] Line 197, /home/travis/build/shanapu/MyStore/addons/sourcemod/scripting/include/smartdm.inc::Downloader_AddFileToDownloadsTable
L 12/08/2019 - 16:07:12: [SM]   [3] Line 188, /home/travis/build/shanapu/MyStore/addons/sourcemod/scripting/include/smartdm.inc::Downloader_AddFileToDownloadsTable
L 12/08/2019 - 16:07:12: [SM]   [4] Line 139, addons/sourcemod/scripting/mystore_item_playermodel.sp::PlayerModels_OnMapStart
L 12/08/2019 - 16:07:12: [SM]   [6] Call_Finish
L 12/08/2019 - 16:07:12: [SM]   [7] Line 758, addons/sourcemod/scripting/mystore_core.sp::OnMapStart
L 12/08/2019 - 16:07:29: [SM] Exception reported: Handle 9940512 is invalid (error 1)
L 12/08/2019 - 16:07:47: SourceMod error session started
L 12/08/2019 - 16:07:47: Info (map "$2000$_classic") (file "csgo\addons\sourcemod\logs\errors_20191208.log")
L 12/08/2019 - 16:07:47: [SM] Exception reported: Invalid convar handle 0 (error 4)
L 12/08/2019 - 16:07:47: [SM] Blaming: mystore_item_attribute.smx
L 12/08/2019 - 16:07:47: [SM] Call stack trace:
L 12/08/2019 - 16:07:47: [SM]   [0] ConVar.BoolValue.get
L 12/08/2019 - 16:07:47: [SM]   [1] Line 164, addons/sourcemod/scripting/mystore_item_attribute.sp::Event_PlayerSpawn
L 12/08/2019 - 16:07:47: [SM] Exception reported: Invalid convar handle 0 (error 4)
L 12/08/2019 - 16:07:47: [SM] Blaming: mystore_item_perspective.smx
L 12/08/2019 - 16:07:47: [SM] Call stack trace:
L 12/08/2019 - 16:07:47: [SM]   [0] ConVar.BoolValue.get
L 12/08/2019 - 16:07:47: [SM]   [1] Line 102, addons/sourcemod/scripting/mystore_item_perspective.sp::Event_PlayerSpawn
L 12/08/2019 - 16:07:47: [SM] Exception reported: Invalid convar handle 0 (error 4)
L 12/08/2019 - 16:07:47: [SM] Blaming: mystore_item_spawnextra.smx
L 12/08/2019 - 16:07:47: [SM] Call stack trace:
L 12/08/2019 - 16:07:47: [SM]   [0] ConVar.BoolValue.get
L 12/08/2019 - 16:07:47: [SM]   [1] Line 136, addons/sourcemod/scripting/mystore_item_spawnextra.sp::Event_PlayerSpawn
L 12/08/2019 - 16:07:47: [CRASH] Accelerator uploaded crash dump: Crash ID: IYTJ-W2OR-I7BN

**Comment by oylsister** [comment] 2020-01-07 15:13
This happened when you put the vtf files in the non-precache section of the sm_downloader. I'm sure that MyStore doesn't precache the files for you, so you have to use the plugin such as sm_downloader, etc.  what I try to explain is I found out that if you precache both of vtf and vtm files, you not gonna have a problem like this.

**Comment by shanapu** [comment] 2020-01-29 01:55
duplicate of https://github.com/shanapu/MyStore/issues/11 we'll continue the issue over there

**Closed by shanapu** 2020-01-29 01:55 UTC
Labels: duplicate, error
